from __future__ import annotations

from enum import StrEnum


class AccessLevel(StrEnum):
    FULL_TEXT = "FULL_TEXT"
    PARTIAL_TEXT = "PARTIAL_TEXT"
    ABSTRACT_ONLY = "ABSTRACT_ONLY"
    METADATA_ONLY = "METADATA_ONLY"


class LifecycleState(StrEnum):
    DISCOVERED = "DISCOVERED"
    SCREENED = "SCREENED"
    QUEUED = "QUEUED"
    READ = "READ"
    REJECTED = "REJECTED"
    REPORTED = "REPORTED"


class RelationshipType(StrEnum):
    CONVERGES_WITH = "CONVERGES_WITH"
    CONTRADICTS = "CONTRADICTS"
    EXTENDS = "EXTENDS"
    METHODOLOGICAL_DIFFERENCE = "METHODOLOGICAL_DIFFERENCE"
    HISTORIOGRAPHIC_SHIFT = "HISTORIOGRAPHIC_SHIFT"
    RESEARCH_GAP = "RESEARCH_GAP"


class FeedbackType(StrEnum):
    VERY_IMPORTANT = "VERY_IMPORTANT"
    USEFUL = "USEFUL"
    IRRELEVANT = "IRRELEVANT"
    READ_PERSONALLY = "READ_PERSONALLY"
    INVESTIGATE_REFERENCES = "INVESTIGATE_REFERENCES"
